### PR TITLE
fix: cherry-pick better local dev for ssh from gpdb close #746

### LINKED ISSUE #746: [Bug] make create-demo-cluster问题
### Apache Cloudberry version

main branch

### What happened

image
执行 make create-demo-cluster以后，由于之前没有ssh localhost，这里就一直打点号

### What you think should happen instead

_No response_

### How to reproduce

不应该有..... 这些输出，没有给用户输入yes or no的间隙

### Operating System

 	Welcome to Huawei Cloud Service  [root@2x86-64-6d1e ~]# cat /etc/os-release NAME="CentOS Linux" VERSION="7 (Core)" ID="centos" ID_LIKE="rhel fedora" VERSION_ID="7" PRETTY_NAME="CentOS Linux 7 (Core)" ANSI_COLOR="0;31" CPE_NAME="cpe:/o:centos:centos:7" HOME_URL="https://www.centos.org/" BUG_REPORT_URL="https://bugs.centos.org/"  CENTOS_MANTISBT_PROJECT="CentOS-7" CENTOS_MANTISBT_PROJECT_VERSION="7" REDHAT_SUPPORT_PRODUCT="centos" REDHAT_SUPPORT_PRODUCT_VERSION="7"

### Anything else

_No response_

### Are you willing to submit PR?

- [ ] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/apache/cloudberry/blob/main/CODE_OF_CONDUCT.md).

### PR DESCRIPTION
**Pull request by yihong0618**
Fixes #746

### What does this PR do?

This PR cherry-pick three commits from gpdb for better local dev.

commit1: add start_new_session
commit2: do not need to ssh if developing cloudberry/gpdb in local env 

commit3: base from coomit1 

for commit2 benefit: as the test before, make test local can also speed up. 

### Type of Change
- [ ] Bug fix (non-breaking change)
- [ ] New feature (non-breaking change)
- [ ] Breaking change (fix or feature with breaking changes)
- [ ] Documentation update

### Test Plan

- [ ] Unit tests added/updated
- [ ] Integration tests added/updated
- [ ] Passed `make installcheck`
- [ ] Passed `make -C src/test installcheck-cbdb-parallel`

### Impact

**Performance:**

**User-facing changes:**

**Dependencies:**

### Checklist
- [ ] Followed [contribution guide](https://cloudberry.apache.org/contribute/code)
- [ ] Added/updated documentation
- [ ] Reviewed code for security implications
- [ ] Requested review from [cloudberry committers](https://github.com/orgs/apache/teams/cloudberry-committers)

### Additional Context

---

This comment should now re-trigger a CI run. The previous skip ci has been removed.

### CODE REVIEW

**Comment by avamingli** [comment]
@yihong0618 Thanks for doing this.

@edespino  CI jobs succeed immediately?

image

image

**Comment by edespino** [comment]
@avamingli - Woah .. that is too fast!

**Comment by edespino** [comment]
It is probably due to the PR template. It has:

⚠️ To skip CI: Add [skip ci] to your PR title. Only use when necessary! ⚠️

**Comment by yihong0618** [comment]
> It is probably due to the PR template. It has:
> 
> 
> 
> ⚠️ To skip CI: Add [skip ci] to your PR title. Only use when necessary! ⚠️

copy, will remember that next time

**Comment by edespino** [comment]
Sorry about that ... I will need to submit a workflow PR tomorrow to only allow a skip in the title.

**Comment by leborchuk** [comment]
Sorry, could you explain how start_new_session is used? I see the new parameter was added in https://github.com/apache/cloudberry/pull/747/commits/0aad1ca4b15016ac7301ce9ab1476b8bf8613484 but it has the False value everywhere, how it is used?

**Comment by yihong0618** [comment]
> Sorry, could you explain how start_new_session is used? I see the new parameter was added in [0aad1ca](https://github.com/apache/cloudberry/commit/0aad1ca4b15016ac7301ce9ab1476b8bf8613484) but it has the False value everywhere, how it is used?

seems its not a necessary arg, but cherry-pick this commit to sync with upstream code is better

**Comment by avamingli** [comment]
> > Sorry, could you explain how start_new_session is used? I see the new parameter was added in [0aad1ca](https://github.com/apache/cloudberry/commit/0aad1ca4b15016ac7301ce9ab1476b8bf8613484) but it has the False value everywhere, how it is used?
> 
> seems its not a necessary arg, but cherry-pick this commit to sync with upstream code is better

Do we miss some commits around that param?

**Comment by avamingli** [comment]
> > > Sorry, could you explain how start_new_session is used? I see the new parameter was added in [0aad1ca](https://github.com/apache/cloudberry/commit/0aad1ca4b15016ac7301ce9ab1476b8bf8613484) but it has the False value everywhere, how it is used?
> > 
> > 
> > seems its not a necessary arg, but cherry-pick this commit to sync with upstream code is better
> 
> Do we miss some commits around that param?

Have a search, the param is true in commit https://github.com/avamingli/gpdb/commit/01bbcb6a085a3880a25211838ab9fb4ca0345da3
which has not  been cherry-picked yet.

**Comment by yihong0618** [comment]
> > > > Sorry, could you explain how start_new_session is used? I see the new parameter was added in [0aad1ca](https://github.com/apache/cloudberry/commit/0aad1ca4b15016ac7301ce9ab1476b8bf8613484) but it has the False value everywhere, how it is used?
> > > 
> > > 
> > > seems its not a necessary arg, but cherry-pick this commit to sync with upstream code is better
> > 
> > 
> > Do we miss some commits around that param?
> 
> Have a search, the param is true in commit [avamingli/gpdb@01bbcb6](https://github.com/avamingli/gpdb/commit/01bbcb6a085a3880a25211838ab9fb4ca0345da3) which has not been cherry-picked yet.

Thanks will cherry-pick it too

**Comment by yihong0618** [comment]
> Hi @yihong0618 , thanks for your help again.
> 
> I see commit: [0aad1ca](https://github.com/apache/cloudberry/commit/0aad1ca4b15016ac7301ce9ab1476b8bf8613484) has the same commit title and message with [12d8566](https://github.com/apache/cloudberry/commit/12d856699f7bcc1dd2a1073ef6806dffb9d6846c) but different codes.
> 
> I guess GPDB has only one commit with that title and message, is there sth wrong?
> 
> image

will try to figure maybe this weekend thanks~

**Comment by yihong0618** [comment]
fixed

**Comment by avamingli** [comment]
> fixed

Thanks for your help.

**Comment by yihong0618** [comment]
failed diff
```diff
diff -I HINT: -I CONTEXT: -I GP_IGNORE: -U3 /__w/cloudberry/cloudberry/src/test/regress/expected/uao_compaction/full_stats.out /__w/cloudberry/cloudberry/src/test/regress/results/uao_compaction/full_stats.out
--- /__w/cloudberry/cloudberry/src/test/regress/expected/uao_compaction/full_stats.out	2024-12-07 23:38:36.283181352 -0800
+++ /__w/cloudberry/cloudberry/src/test/regress/results/uao_compaction/full_stats.out	2024-12-07 23:38:36.287181360 -0800
@@ -32,6 +32,6 @@
 SELECT relname, reltuples FROM pg_class WHERE relname = 'uao_full_stats_index';
        relname        | reltuples 
 ----------------------+-----------
- uao_full_stats_index |        85
+ uao_full_stats_index |       185
 (1 row)
 
diff -I HINT: -I CONTEXT: -I GP_IGNORE: -U3 /__w/cloudberry/cloudberry/src/test/regress/expected/uao_compaction/stats.out /__w/cloudberry/cloudberry/src/test/regress/results/uao_compaction/stats.out
--- /__w/cloudberry/cloudberry/src/test/regress/expected/uao_compaction/stats.out	2024-12-07 23:38:36.663182147 -0800
+++ /__w/cloudberry/cloudberry/src/test/regress/results/uao_compaction/stats.out	2024-12-07 23:38:36.667182155 -0800
@@ -38,7 +38,7 @@
 SELECT relname, reltuples FROM pg_class WHERE relname = 'uao_stats_index';
      relname     | reltuples 
 -----------------+-----------
- uao_stats_index |        88
+ uao_stats_index |       151
 (1 row)
 
 -- re-setup for next case

```

**Review by yjhjstz — APPROVED** [review]
LGTM

**Review by my-ship-it — APPROVED** [review]
LGTM

**Pull request merged**
