### PR TITLE
Make gp-style partition table compatible with greenplum

### PR DESCRIPTION
**Pull request by gfphoenix78**
Adding a new partition should have the same behavior like greenplum 6/7.
The child partition inherits access method, reloptions, column encodings
from its parent if no specific options are provided

---

### Change logs

_Describe your change clearly, including what problem is being solved or what feature is being added._

_If it has some breaking backward or forward compatibility, please clary._

### Why are the changes needed?

_Describe why the changes are necessary._

### Does this PR introduce any user-facing change?

_If yes, please clarify the previous behavior and the change this PR proposes._

### How was this patch tested?
```sql
CREATE TABLE star.trd_fct (
trd_date_key date NOT NULL ,
prod_key integer NOT NULL ,
cust_key integer NOT NULL ,
notional_val numeric(20,10) ,
num_of_shares integer ,
num_of_trades integer ,
trd_id bigint NOT NULL ,
ins_ts timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL
)

WITH (
appendoptimized=true
,orientation=row
,compresstype=zlib
,compresslevel=5
)
DISTRIBUTED RANDOMLY
PARTITION BY RANGE (trd_date_key) (
START ('2020-01-01'::date) INCLUSIVE
END ('2027-01-01'::date) EXCLUSIVE
EVERY (interval '1 Year')
)
;

alter table star.trd_fct add partition start ('2027-01-01') inclusive end ('2028-01-01') exclusive;
```

_Please detail how the changes were tested, including manual tests and any relevant unit or integration tests._

### Contributor's Checklist

Here are some reminders and checklists before/when submitting your pull request, please check them:

- [ ] Make sure your Pull Request has a clear title and commit message. You can take [git-commit](https://github.com/cloudberrydb/cloudberrydb/blob/main/.gitmessage) template as a reference.
- [ ] Sign the Contributor License Agreement as prompted for your first-time contribution(*One-time setup*).
- [ ] Learn the [coding contribution guide](https://cloudberrydb.org/contribute/code), including our code conventions, workflow and more.
- [ ] List your communication in the [GitHub Issues](https://github.com/cloudberrydb/cloudberrydb/issues) or [Discussions](https://github.com/orgs/cloudberrydb/discussions) (if has or needed).
- [ ] Document changes.
- [ ] Add tests for the change
- [ ] Pass `make installcheck`
- [ ] Pass `make -C src/test installcheck-cbdb-parallel`
- [ ] Feel free to request `cloudberrydb/dev` team for review and approval when your PR is ready🥳

### CODE REVIEW

**Comment by my-ship-it** [comment]
Please add some test cases, thanks

**Comment by reshke** [comment]
Hi, I have failure with this change 

```
db2=# \d+ star.trd_fct
row number 0 is out of range 0..-1
row number 0 is out of range 0..-1
cannot duplicate null pointer (internal error)
```

**Comment by reshke** [comment]
> Hi, I have failure with this change
> 
> ```
> db2=# \d+ star.trd_fct
> row number 0 is out of range 0..-1
> row number 0 is out of range 0..-1
> cannot duplicate null pointer (internal error)
> ```

Oh, sorry, looks like this is not related to current pr. I will take a look. Issue persist on master

**Comment by reshke** [comment]
> Hi, I have failure with this change
> 
> ```
> db2=# \d+ star.trd_fct
> row number 0 is out of range 0..-1
> row number 0 is out of range 0..-1
> cannot duplicate null pointer (internal error)
> ```

https://github.com/cloudberrydb/cloudberrydb/issues/697

**Comment by reshke** [comment]
I found another issue https://github.com/cloudberrydb/cloudberrydb/issues/698. we can fix this within this pr, or i can created separate pr for this.

**Comment by gfphoenix78** [comment]
> Please add some test cases, thanks

Sure, the PR isn't  fully ready yet. I'll some the full test when inherited encoding attributes are supported.

**Review by reshke — APPROVED** [review]
Ok, now lets run the tests.

**Review by reshke — APPROVED** [review]

**Comment by tuhaihe** [comment]
Hi @reshke Do you link your GitHub account with your Apache ID? It seems that your approval does not have binding access. Welcome to visit https://gitbox.apache.org/boxer/ to double-check.

**Review by reshke — APPROVED** [review]

**Review by avamingli — APPROVED** [review]

**Pull request merged**
