### PR TITLE
[skip ci] Doc: fix org change that link dead for discuss

### PR DESCRIPTION
**Pull request by yihong0618**
fix #ISSUE_Number

---

### Change logs

As cloudberry the org changed to apache now, most of the links can redirect but for the discuss such as orgs/cloudberry/discuss can not, this PR fix that case.
you can try:
link dead:  https://github.com/orgs/cloudberrydb/discussions/categories/proposal
link fixed:    url: https://github.com/apache/cloudberrydb/discussions/categories/proposal

for the case it may  graduate from apache some day so keep the urls can redirect first.

### Why are the changes needed?

_Describe why the changes are necessary._

### Does this PR introduce any user-facing change?

_If yes, please clarify the previous behavior and the change this PR proposes._

### How was this patch tested?

_Please detail how the changes were tested, including manual tests and any relevant unit or integration tests._

### Contributor's Checklist

Here are some reminders and checklists before/when submitting your pull request, please check them:

- [ ] Make sure your Pull Request has a clear title and commit message. You can take [git-commit](https://github.com/cloudberrydb/cloudberrydb/blob/main/.gitmessage) template as a reference.
- [ ] Sign the Contributor License Agreement as prompted for your first-time contribution(*One-time setup*).
- [ ] Learn the [coding contribution guide](https://cloudberrydb.org/contribute/code), including our code conventions, workflow and more.
- [ ] List your communication in the [GitHub Issues](https://github.com/cloudberrydb/cloudberrydb/issues) or [Discussions](https://github.com/orgs/cloudberrydb/discussions) (if has or needed).
- [ ] Document changes.
- [ ] Add tests for the change
- [ ] Pass `make installcheck`
- [ ] Pass `make -C src/test installcheck-cbdb-parallel`
- [ ] Feel free to request `cloudberrydb/dev` team for review and approval when your PR is ready🥳

### CODE REVIEW

**Review by avamingli — DISMISSED** [review]
LGTM. Thanks.

**Comment by tuhaihe** [comment]
Hi @yihong0618, thank you! There is already a PR #696 for the link changes. Please feel free to rebase your commit once #696 is merged. 

BTW, welcome to take the [git commit template](https://github.com/cloudberrydb/cloudberrydb/blob/main/.gitmessage) to amend your commit title and body. Thanks again!

**Comment by yihong0618** [comment]
@tuhaihe the issue created is dead in cloudberry it will link a 404 page, maybe we can merge this two pull requests

**Comment by tuhaihe** [comment]
> @tuhaihe the issue created is dead in cloudberry it will link a 404 page, maybe we can merge this two pull requests

Agreed. Welcome to rebase to trigger the CI (now can use the tag ‘skip ci ‘ to skip the checks) then merge it.

**Review by tuhaihe — CHANGES_REQUESTED** [review]
Hi @yihong0618 welcome to resolve the conflicts.

**Comment by yihong0618** [comment]
> Hi @yihong0618 welcome to resolve the conflicts.
> 
> Also please amend your commit messages per the template - https://github.com/apache/cloudberry/blob/main/.gitmessage, thanks.

done

**Review by tuhaihe — APPROVED** [review]

**Comment by tuhaihe** [comment]
Hi @edespino add the tag `skip ci` to the PR title, but seems that cannot skip the build. FYI.

**Comment by edespino** [comment]
@tuhaihe - I believe the `[skip ci]` will work but it has be in the PR title when the PR is created. Please give it a try with the next PR which does not need a build. You can also test it with a draft PR and then close it.

**Review by gfphoenix78 — APPROVED** [review]

**Pull request merged**
