### PR TITLE
Fix test cases for gp-style partition in single-node mode

### PR DESCRIPTION
**Pull request by gfphoenix78**
The commit 782d9b799 fixes inheritance issue on gp-style partition table. The test cases for single-node are not fixed yet.

### Type of Change
- [ ] Bug fix (non-breaking change)
- [ ] New feature (non-breaking change)
- [ ] Breaking change (fix or feature with breaking changes)
- [ ] Documentation update

### Test Plan

- [ ] Unit tests added/updated
- [ ] Integration tests added/updated
- [ ] Passed `make installcheck`
- [ ] Passed `make -C src/test installcheck-cbdb-parallel`

### Impact

**Performance:**

**User-facing changes:**

**Dependencies:**

### Checklist
- [ ] Followed [contribution guide](https://cloudberry.apache.org/contribute/code)
- [ ] Added/updated documentation
- [ ] Reviewed code for security implications
- [ ] Requested review from [cloudberry committers](https://github.com/orgs/apache/teams/cloudberry-committers)

### Additional Context

⚠️ **To skip CI:** Add `[skip ci]` to your PR title. Only use when necessary! ⚠️

---

### CODE REVIEW

**Comment by edespino** [comment]
@gfphoenix78 - I will share the changes necessary to enable the singlenode tests with this PR.

**Comment by edespino** [comment]
@gfphoenix78: I have a commit based on your PR branch that will enable the `singlenode` tests. 

Branch: https://github.com/edespino/cloudberry/tree/refs/heads/pr-736-singlenode
Commit: https://github.com/edespino/cloudberry/commit/273c0a0d0d3b149c1ab2a05a6bf6892c82bccf69
Workflow shows the standalone test schedules have passed: https://github.com/edespino/cloudberry/actions/runs/12063579565

**Comment by edespino** [comment]
@gfphoenix78 Hey buddy ... the green singlenode tests are beautiful! 众人拾柴火焰高

**Review by edespino — APPROVED** [review]
+1 - Nice quick work! Thank you.

**Comment by gfphoenix78** [comment]
This PR should keep the two commits, please don't squash them. These two commits are independent, but both of them contribute to the pipeline. The second commit is to enable test pipeline for single-node mode, which will fail without the first commit.
In short, the first commit fixes test failures, and the second commit enables to run these tests and proves it.

**Review by edespino — APPROVED** [review]
+1 - The singlenode tests are now passing. Nice work.

**Review by my-ship-it — APPROVED** [review]

**Pull request merged**
